name: DiceEaster
version: 1.4.1
description: DiceEaster
author: Ste3et_C0st
website: http://dicecraft.de
depend: [Vault, HolographicDisplays]
softdepend: [TitleManager, BarAPI]
main: de.Ste3et_C0st.DiceEaster.main
commands: 
  easter:
    description:  DiceEaster Egg Command
    usage:  /<command>